version: "3.8"
services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password # Heroku ignores it anyway
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 11484 cable/config.ru
    ports:
      - '11484:11484'
    volumes:
      - '.:/app'
volumes:
  redis:
  postgres:
